import { DataContextProvider } from '@/store/store'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <DataContextProvider>
        <body className={inter.className + ' flex flex-col h-screen bg-gray-100'}>
          <header className='text-center text-white bg-slate-800 w-full h-10 mb-4'>
            header
          </header>
          <div className="container flex flex-col justify-center h-full">
            {children}
          </div>
          <footer className='text-center text-white bg-slate-800 w-full h-10 mt-4'>
            footer
          </footer>
        </body>
      </DataContextProvider>
    </html>
  )
}
