import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' flex flex-col h-screen p-4 bg-gray-100'}>
        <header className='text-center bg-white rounded-lg shadow-md mb-4'>
          header
        </header>
        {children}
        <footer className='text-center bg-white rounded-lg shadow-md mt-4'>
          footer
        </footer>
      </body>
    </html>
  )
}
